DEBUG_MODE = False

SERVER_IP = '172.24.21.99'
PORT = 10021

REMOTE_EVENT_CREATE_CARD = 0
REMOTE_EVENT_MOVE_CARD   = 1
REMOTE_EVENT_TURN_CARD   = 2
REMOTE_EVENT_TAP_CARD    = 3
REMOTE_EVENT_REMOVE_CARD = 4

DECK_STATUS_PREPARE = 0
DECK_STATUS_INUSE   = 1

CARD_ANIM_STATUS_NORMAL  = 0
CARD_ANIM_STATUS_GOTO    = 1

ANIM_STATUS_NORMAL = 0
ANIM_STATUS_GOTO   = 1

CARD_STATUS_ONDESK       = 10
CARD_STATUS_ONMOUSE      = 11
CARD_STATUS_INHAND       = 12
CARD_STATUS_INHAND_OUT   = 13
CARD_STATUS_INCOLLECTION = 14
CARD_STATUS_OPPONENT_INHAND = 15
CARD_STATUS_OPPONENT_INLIB  = 16
CARD_STATUS_INLIB        = 17

CARD_FROM_NONE = 0
CARD_FROM_HAND = 1
CARD_FROM_DESK = 2
CARD_FROM_LIB  = 3
CARD_FROM_GRAVEYARD = 4

HP_PANEL_ZINDEX = -2
CARD_VIEWER_ZINDEX = -1
DECK_ZINDEX = OPPONENT_DECK_ZINDEX = GRAVEYARD_ZINDEX = OPPONENT_GRAVEYARD_ZINDEX = -1
CARD_DRAWOUT_ZINDEX = 800
HANDCARD_ZINDEX = 1000
CARDCOLLECTION_VIEWER_ZINDEX = 2000
CARD_INCCVIEWER_ZINDEX = 2001
CARD_GOING_ZINDEX = 5000
DECK_SELECTOR_ZINDEX = 6000
DECK_SELECTOR_ITEM_ZINDEX = 6001
MESSAGE_ZINDEX = 10000

MOUSEBUTTONDOWN_LEFT  = 0
MOUSEBUTTONDOWN_RIGHT = 1
MOUSE_HOVER           = 3
MOUSE_UNHOVER         = 4

OPPONENT_HANDCARD_TOP = -50;
HANDCARD_TOP = 550
HANDCARD_LEFT = 134
HANDCARD_OUT_TOP = 510
HANDCARD_SPACING = 15

CARDCOLLECTION_VIEWER_TOP = 400
CARDCOLLECTION_STATE_HIDDEN = 0
CARDCOLLECTION_STATE_SHOW   = 1

GAME_STATUS_NORMAL = 0
GAME_STATUS_CCVIEW = 1
GAME_STATUS_SELECT_DECK = 2

MESSAGE_LIFE = 4        # seconds
MESSAGE_HEIGHT = 25
MESSAGE_SPACING = 15
MESSAGEPOOL_TOP = 240

CardInfoLibFile = 'card.lib'
DECKS_DIR = '..\\decks'

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 600

CARDVIEWER_STATUS_HIDE = 0
CARDVIEWER_STATUS_SHOW = 1

COLOR_GREY = 0
COLOR_RED  = 1
COLOR_BLUE = 2
COLOR_GREEN = 3
COLOR_WHITE = 4
COLOR_BLACK = 5

DECK_SELECTOR_ITEM_SPACING = 3
SIZE_DECK_SELECTOR_ITEM = (280,25)
SIZE_DECK_SELECTOR = (300, 400)

pos_deckselectoritem = (312,160)
pos_deckselector = (312,150)

SIZE_HP_PANEL = (50,50)
pos_hp_panel = (137,275)

size_orignal = (192, 276)
size_small = (64, 92)


img_cardback = "facedown.jpg"

pos_battlefield_top = (324,0)
img_battlefield_top = 'battlefield_top.gif'

pos_battlefield_bottom = (324, 300)
img_battlefield_bottom = 'battlefield_bottom.gif'

pos_sidebg = (0,0)
img_sidebg = 'new_sidebg2.jpg'

pos_cardviewer = (6,50)

pos_opponent_library   = (SCREEN_WIDTH-70, 40)
pos_opponent_graveyard = (SCREEN_WIDTH-70, 190)
pos_graveyard          = (SCREEN_WIDTH-70, 320)
pos_library            = (SCREEN_WIDTH-70, 440)

pos_message = (554, 240)

pos_player_hp = (5,550)